// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS08Jc5ThpSvGPkohy1Xs60QecGjaGqYM',
    appId: '1:1017268067160:web:ca944abce83fe8d632e32d',
    messagingSenderId: '1017268067160',
    projectId: 'karigar-samarthan',
    authDomain: 'karigar-samarthan.firebaseapp.com',
    storageBucket: 'karigar-samarthan.firebasestorage.app',
    measurementId: 'G-2NC6CV7QWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ugyDzh7nkqDAgZbwDvDo_da0qfrvrmw',
    appId: '1:1017268067160:android:89c23d1b7fb019a632e32d',
    messagingSenderId: '1017268067160',
    projectId: 'karigar-samarthan',
    storageBucket: 'karigar-samarthan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC82Nez0ionATdoBUwFtCgwmXAg0_owIxM',
    appId: '1:1017268067160:ios:e6ef44f860ad71b532e32d',
    messagingSenderId: '1017268067160',
    projectId: 'karigar-samarthan',
    storageBucket: 'karigar-samarthan.firebasestorage.app',
    iosBundleId: 'com.example.karigarSamarthan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC82Nez0ionATdoBUwFtCgwmXAg0_owIxM',
    appId: '1:1017268067160:ios:e6ef44f860ad71b532e32d',
    messagingSenderId: '1017268067160',
    projectId: 'karigar-samarthan',
    storageBucket: 'karigar-samarthan.firebasestorage.app',
    iosBundleId: 'com.example.karigarSamarthan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS08Jc5ThpSvGPkohy1Xs60QecGjaGqYM',
    appId: '1:1017268067160:web:820d1f388e07adeb32e32d',
    messagingSenderId: '1017268067160',
    projectId: 'karigar-samarthan',
    authDomain: 'karigar-samarthan.firebaseapp.com',
    storageBucket: 'karigar-samarthan.firebasestorage.app',
    measurementId: 'G-0553XKX114',
  );

}